"""translation_usage

Revision ID: 0c29b039b670
Revises: bb8b48523166
Create Date: 2026-08-06 20:13:44.735664

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c29b039b670"
down_revision: str | Sequence[str] | None = "bb8b48523166"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("chars_sent", sa.Integer(), nullable=False),
        sa.Column("sentences", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("translation_usage", schema=None) as batch_op:
        batch_op.create_index("ix_translation_usage_created", ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("translation_usage", schema=None) as batch_op:
        batch_op.drop_index("ix_translation_usage_created")

    op.drop_table("translation_usage")
    # ### end Alembic commands ###
