"""user_words, contexts, word_occurrences

Revision ID: 5b2e9baa556e
Revises: 0c29b039b670
Create Date: 2026-08-07 09:10:53.841474

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b2e9baa556e"
down_revision: str | Sequence[str] | None = "0c29b039b670"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("headword", sa.String(length=64), nullable=False),
        sa.Column("reading", sa.String(length=128), nullable=True),
        sa.Column("user_translation", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("ease", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lang", "headword", name="uq_user_words_lang_headword"),
    )
    op.create_table(
        "word_occurrences",
        sa.Column("headword", sa.String(length=64), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("headword", "chapter_id"),
    )
    with op.batch_alter_table("word_occurrences", schema=None) as batch_op:
        batch_op.create_index("ix_word_occurrences_headword", ["headword"], unique=False)

    op.create_table(
        "contexts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_word_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=True),
        sa.Column("sentence_id", sa.Integer(), nullable=True),
        sa.Column("sentence", sa.Text(), nullable=False),
        sa.Column("offset_start", sa.Integer(), nullable=False),
        sa.Column("offset_end", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("offset_end >= offset_start", name="ck_contexts_offsets"),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sentence_id"], ["sentences.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_word_id"], ["user_words.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contexts", schema=None) as batch_op:
        batch_op.create_index("ix_contexts_user_word", ["user_word_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contexts", schema=None) as batch_op:
        batch_op.drop_index("ix_contexts_user_word")

    op.drop_table("contexts")
    with op.batch_alter_table("word_occurrences", schema=None) as batch_op:
        batch_op.drop_index("ix_word_occurrences_headword")

    op.drop_table("word_occurrences")
    op.drop_table("user_words")
    # ### end Alembic commands ###
