"""dict_entries

Revision ID: bb8b48523166
Revises: 774cd4aef341
Create Date: 2026-08-06 17:40:39.183499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb8b48523166"
down_revision: str | Sequence[str] | None = "774cd4aef341"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dict_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("headword", sa.String(length=64), nullable=False),
        sa.Column("traditional", sa.String(length=64), nullable=True),
        sa.Column("reading", sa.String(length=128), nullable=True),
        sa.Column("reading_numbered", sa.String(length=128), nullable=True),
        sa.Column("pos", sa.String(length=32), nullable=True),
        sa.Column("senses_json", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("freq", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dict_entries", schema=None) as batch_op:
        batch_op.create_index("ix_dict_entries_lookup", ["lang", "headword"], unique=False)
        batch_op.create_index("ix_dict_entries_source", ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dict_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_dict_entries_source")
        batch_op.drop_index("ix_dict_entries_lookup")

    op.drop_table("dict_entries")
    # ### end Alembic commands ###
